service:

    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kuala_Lumpur
            - WEBUI_PORT=8081
            - TORRENTING_PORT=16881
            - UMASK=022
        volumes:
            - ./qbittorrent:/config
            - /home/family/Downloads:/downloads
        ports:
            - 8081:8081
            - 16881:16881
            - 16881:16881/udp
        restart: unless-stopped
