networks:
  ARRS:
    driver: bridge
    ipam:
      config:
        - subnet: 192.19.0.0/24
          gateway: 192.19.0.1

services:

  portainer:
    image: 'portainer/portainer-ce:latest'
    container_name: 'portainer'
    ports:
      - '9001:9000'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './portainer:/data'
    restart: 'unless-stopped'
    networks:
      ARRS:
        ipv4_address: '192.19.0.2'

  prowlarr:
    image: 'lscr.io/linuxserver/prowlarr:latest'
    container_name: 'prowlarr'
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Asia/Kuala_Lumpur'
      - 'UMASK=022'
    ports:
      - '9002:9696'
    volumes:
      - './prowlarr:/config'
      - '/media/torrents:/downloads'
      - '/media/local:/media'
    restart: 'unless-stopped'
    networks:
      ARRS:
        ipv4_address: '192.19.0.3'
  
  jackett:
    image: 'lscr.io/linuxserver/jackett:latest'
    container_name: 'jackett'
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Asia/Kuala_Lumpur'
      - 'UMASK=022'
      - 'AUTO_UPDATE=true'
      - 'RUN_OPTS=true'
    ports:
      - '9003:9117'
    volumes:
      - './jackett:/data'
      - '/media/torrents:/downloads'
      - '/media/local:/media'
    restart: 'unless-stopped'
    networks:
      ARRS:
        ipv4_address: '192.19.0.4'

  radarr:
    image: 'lscr.io/linuxserver/radarr:latest'
    container_name: radarr
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Asia/Kuala_Lumpur'
      - 'UMASK=022'
    ports:
      - '9004:7878'
    devices:
      - '/dev/sda1:/drive1'
    volumes:
      - './radarr:/config'
      - '/media/torrents/movies:/media/downloads'
      - '/drive1/media/movies:/media/drive'
      - '/media/local/movies:/media/local'
    restart: 'unless-stopped'
    networks:
      ARRS:
        ipv4_address: '192.19.0.5'

  sonarr:
    image: 'lscr.io/linuxserver/sonarr:latest'
    container_name: sonarr
    environment: 
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Asia/Kuala_Lumpur'
      - 'UMASK=022'
    ports:
      - '9005:8989'
    devices:
      - 'dev/sda1:/drive1'
    volumes:
      - './sonarr:/config'
      - '/media/local/tvshows:/media/local/tvshows'
      - '/media/local/drama:/media/local/drama'
      - '/media/local/anime:/media/local/anime'
      - '/media/torrents/tvshows:/downloads/tvshows'
      - '/media/torrents/drama:/downloads/drama'
      - '/media/torrents/anime:/downloads/anime'
      - '/drive1/media/tvshows:/media/drive/tvshows'
      - '/drive1/media/drama:/media/drive/drama'
      - '/drive1/media/anime:/media/drive/anime'
    restart: 'unless-stopped'
    networks:
      ARRS:
        ipv4_address: '192.19.0.6'

  whisparr:
    image: 'ghcr.io/hotio/whisparr:latest'
    container_name: 'whisparr'
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Asia/Kuala_Lumpur'
      - 'UMASK=022'
    ports:
      - '9006:6969'
    devices:
      - '/dev/sda1:/drive'
    volumes:
      - './whisparr:/config'
      - '/media/torrents/x:/downloads'
      - '/media/local/x:/media/local'
      - '/drive/media/x:/media/drive'
    restart: 'unless-stopped'
    networks:
      ARRS:
        ipv4_address: '192.19.0.7'

  autobangumi:
    image: 'ghcr.io/estrellaxd/auto_bangumi:latest'
    container_name: 'autobangumi'
    environment: 
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Asia/Kuala_Lumpur'
      - 'UMASK=022'
    ports:
      - '9696:9696'
    restart: 'unless-stopped'

  flaresolverr:
    image: 'ghcr.io/flaresolverr/flaresolverr:latest'
    container_name: flaresolverr
    environment:
      - 'LOG_LEVEL=info'
      - 'LOG_HTML=${LOG_HTML:-false}'
      - 'CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}'
      - 'TZ=Asia/Kuala_Lumpur'
    ports:
      - '6001:8191'
    restart: 'unless-stopped'
    networks:
      ARRS:
        ipv4_address: '192.19.0.9'

  jproxy:
    image: 'luckypuppy514/jproxy:latest'
    container_name: jproxy
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Asia/Kuala_Lumpur'
      - JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '6002:8191'
    restart: 'unless-stopped'
    networks:
      ARRS:
        ipv4_address: '192.19.0.10'

  aria2:
    image: 'superng6/aria2:a2b-latest'
    container_name: 'aria2'
    network_mode: 'host'
    cap_add:
      - 'NET_ADMIN'
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Asia/Kuala_Lumpur'
      - 'SECRET=qwer1234'
      - 'CACHE=512M'
      - 'PORT=6800'
      - 'WEBUI=true'
      - 'WEBUI_PORT=9007'
      - 'BTPORT=32516'
      - 'UT=true'
      - 'QUIET=true'
      - 'SMD=true'
      - 'A2B=true'
      - 'CRA2B=2h'
    volumes:
      - './aria2:/config'
      - '~/downloads:/downloads'
      - '/media/torrents:/torrents'
      - '/lib/modules:/lib/modules'
    restart: unless-stopped

  transmission:
    image: 'linuxserver/transmission:latest'
    container_name: transmission
    environment: 
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Asia/Kuala_Lumpur'
      - 'UMASK_SET=022'
      - 'USER=admin'
      - 'PASS=admin'
    devices:
      - '/dev/sda1:/drive'
    volumes:
      - './transmission:/config'
      - '/media/torrents:/downloads/incomplete'
      - '/media/local:/downloads/complete'
      - './transmission/watch:/watch'
      - '/drive/media:/drive'
    ports:
      - '9008:9091'
      - '51413:51413'
      - '51413:51413/udp'
    restart: 'unless-stopped'
    networks:
      ARRS:
        ipv4_address: '192.19.0.11'

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
      - UMASK=022
    devices:
      - /dev/sda1:/drive
    volumes:
      - ./qbittorrent:/config
      - /media/torrents:/downloads/incomplete
      - /media/local:/downloads/complete
      - /drive/media:/drive
    ports:
      - 9009:8080
      - 16881:6881
      - 16881:6881/udp
    restart: unless-stopped
    networks:
      ARRS:
        ipv4_address: '192.19.0.12'

  plex:
    image: 'lscr.io/linuxserver/plex:latest'
    container_name: plex
    network_mode: host
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Asia/Kuala_Lumpur'
      - 'VERSION=docker'
      - 'UMASK_SET=022'
    devices:
      - '/dev/sda1:/drive'
    volumes:
      - './plex:/config'
      - '/media/local:/media/local'
      - '/drive/media:/media/drive'
    restart: 'unless-stopped'

  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - './diun:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - 'TZ=Asia/Kuala_Lumpur'
      - 'DIUN_WATCH_WORKERS=20'
      - 'DIUN_WATCH_SCHEDULE=0 */6 * * *'
      - 'DIUN_WATCH_JITTER=30s'
      - 'DIUN_PROVIDERS_DOCKER=true'
    labels:
      - 'diun.enable=true'
    restart: 'always'

  tautulli:
    image: 'lscr.io/linuxserver/tautulli:latest'
    container_name: 'tautulli'
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Asia/Kuala_Lumpur'
    volumes:
      - './tautulli:/config'
    ports:
      - 9010:8181
    restart: unless-stopped
    networks:
      ARRS:
        ipv4_address: '192.19.0.13'

  overseerr:
    image: 'lscr.io/linuxserver/overseerr:latest'
    container_name: 'overseerr'
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Asia/Kuala_Lumpur'
    volumes:
      - './overseerr:/config'
    ports:
      - '9011:5055'
    restart: 'unless-stopped'
    networks:
      ARRS:
        ipv4_address: '192.19.0.14'
