homeassistant: false
frontend: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost:1883
serial:
  port: /dev/ttyACM0
advanced:
  network_key: GENERATE
  pan_id: GENERATE
  ext_pan_id: GENERATE
