# Indicates the configuration version (used by configuration migrations)
version: 4

# Home Assistant integration (MQTT discovery)
homeassistant:
    enabled: false

# Enable the frontend, runs on port 8080 by default
frontend:
    enabled: true
    port: 9699

# MQTT settings
mqtt:
    # MQTT base topic for zigbee2mqtt MQTT messages
    base_topic: zigbee2mqtt
    # MQTT server URL
    server: 'mqtt://localhost'
    # MQTT server authentication, uncomment if required:
    user: admin
    password: qwer1234

# Serial settings, only required when Zigbee2MQTT fails to start with:
#   USB adapter discovery error (No valid USB adapter found).
#   Specify valid 'adapter' and 'port' in your configuration.
serial:
#     # Location of the adapter
#     # USB adapters - use format "port: /dev/serial/by-id/XXX"
#     # Ethernet adapters - use format "port: tcp://192.168.1.12:6638"
    port: /dev/ttyUSB0
#     # Adapter type, allowed values: `zstack`, `ember`, `deconz`, `ziga>
    adapter: ember

# Periodically check whether devices are online/offline
availability:
    enabled: true

# Advanced settings
advanced:
    channel: 25
    # Let Zigbee2MQTT generate a network key on first start
    network_key: GENERATE
    # Let Zigbee2MQTT generate a pan_id on first start
    pan_id: GENERATE
    # Let Zigbee2MQTT generate a ext_pan_id on first start
    ext_pan_id: GENERATE
