services:

    transmission:
        image: linuxserver/transmission:latest
        container_name: transmission
        environment: 
            - 'PUID=1000'
            - 'PGID=1000'
            - 'TZ=Asia/Kuala_Lumpur'
            - 'UMASK_SET=022'
            - 'USER=admin'
            - 'PASS=admin'
        volumes:
            - /home/family/Downloads:/downlaods
            - /etc/transmission:/config
        ports:
            - 9091:9091
            - 51413:51413
            - 51413:51413/udp
        restart: unless-stopped
