services: 
  portainer:
    -images:portainer/portainer-ce:latest
  container_name: portainer
  restart: always
  ports:
    - "8000:8000"
    - :9443:9443"
    - "9000:9000"
  volumes:
    - /var/run/docker.sock:/var/run/docker.so>
    - ./data:/data
