services:

    whisparr:
    image: 'ghcr.io/hotio/whisparr:latest'
    container_name: whisparr
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Asia/Kuala_Lumpur'
      - 'UMASK=022'
    volumes:
      - './whisparr:/config'
      - '/media/local:/media/local'
      - '/media/torrent:/media/torrent'
      - '~/Downloads:/downloads'
    restart: 'unless-stopped'
