services:
    sonarr:
    image: 'lscr.io/linuxserver/sonarr:latest'
    container_name: sonarr
    environment: 
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Asia/Kuala_Lumpur'
      - 'UMASK=022'
    volumes:
      - './sonarr:/config'
      - '/media/local:/media/local'
      - '/media/torrent:/media/torrent'
      - '~/Downloads:/downloads'
    ports:
      - '8989:8989'
    restart: 'unless-stopped'
